package:
  name: lens
  version: "2.63"

source:
  fn: Lens.tgz
  url: https://github.com/chendaniely/multi-agent-neural-network/raw/master/Lens.tgz
  sha256: cb9e4bd1fc790bb3248b8eb5edac896372b51a7421f847280f843d07ab0220b3

build:
  number: 0

requirements:
  build:
    - xorg-libx11
  run:
    - xorg-libx11

test:
  commands:
    - lens -batch exit

about:
  home: http://web.stanford.edu/group/mbc/LENSManual/index.html
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  # It is strongly encouraged to include a license file in the package,
  # (even if the license doesn't require it) using the license_file entry.
  # See http://conda.pydata.org/docs/building/meta-yaml.html#license-file
  summary: 'the light, efficient network simulator'

  # The remaining entries in this section are optional, but recommended
  description: |
    LENS
  doc_url: http://web.stanford.edu/group/mbc/LENSManual/index.html
  dev_url: http://web.stanford.edu/group/mbc/LENSManual/index.html

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - chendaniely
